src/orders/urls.py
from django.urls import path, re_path
from . import views


app_name = "orders"

urlpatterns = [
    path('cart/', views.view_cart, name='view-cart'),
    path('edit_cart/', views.edit_cart, name='edit-cart'),
    path('delete/<int:pk>/', views.DeleteCartBook.as_view(), name='delete-cart'),
    path('order_complete/', views.CreateOrder.as_view(), name='order-complete'),
    path('user_orders/', views.UserOrders.as_view(), name='user-orders'),
    path('order_update/<int:pk>/', views.UpdateOrder.as_view(), name='order-update'),
    path('orderslist/', views.ListOrders.as_view(), name='orders-list'),
   
]

src/proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from homepage.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('', index),
    path('refs/', include('references.urls', namespace="references")),
    path('goods/', include('goods.urls', namespace="goods")),
    path('orders/', include('orders.urls', namespace="orders"))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
statuses = (
    ('In progress', "In progress"),
    ('Sended', "Sended"),
    ('Done', "Done"),
)

# Create your models here.


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='User cart',
        related_name='carts',
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )
    def total_quantity(self):
        all_books_in_cart = self.book.all()
        total_quantity = 0
        for books_quantity in all_books_in_cart:
            total_quantity += books_quantity.quantity
        return total_quantity

    def total_price(self):
        total_price_in_cart = self.book.all()
        total_price = 0
        for price in total_price_in_cart:
            total_price += price.price_per_position()
        return total_price

    # def __str__(self):
    #     return self.user

class BookinCart(models.Model):
    book = models.ForeignKey(
        "goods.GoodsBooks",
        verbose_name='Book in a cart',
        on_delete=models.PROTECT,
    )
    cart = models.ForeignKey(
        "orders.Cart",
        verbose_name='Cart',
        related_name='book',
        on_delete=models.PROTECT,
    )
    quantity = models.IntegerField(
        verbose_name='Quantity',
        default=1
    )
    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
    )
    create_date = models.DateTimeField(
        "Create date",
        auto_now=False,
        auto_now_add=True
    )
    update_date = models.DateTimeField(
        "Update date",
        auto_now=True,
        auto_now_add=False
    )
    def price_per_position(self):
        return self.price * self. quantity

    def __str__(self):
        return self.book

class Order(models.Model):
    status = models.CharField(
        verbose_name='Status',
        max_length=20,
        choices=statuses,
        default='In progress'
    )
    cart = models.OneToOneField(
        "orders.Cart",
        verbose_name='Cart',
        related_name='order',
        on_delete=models.PROTECT,
    )
    phone = models.CharField(
        verbose_name='Phone',
        max_length=50,
    )
    name = models.CharField(
        verbose_name='Name',
        max_length=20
    )
    adress = models.CharField(
        verbose_name='Adress',
        max_length=100,
    )
    email = models.EmailField(
        verbose_name='Email',
        max_length=100,
    )
    info = models.TextField(
        verbose_name='Info',
        max_length=500,
    )
    create_date = models.DateTimeField(
        "Create date",
        auto_now=False,
        auto_now_add=True
    )
    update_date = models.DateTimeField(
        "Update date",
        auto_now=True,
        auto_now_add=False
    )

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'icons/bootstrap-icons.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" rel="stylesheet"></script>
    <title>{% block title %}
    
    {% endblock title %}</title>
</head>

<body class="d-flex flex-column h-100">
    
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #62a3d0">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">На главную страницу</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'orders:user-orders' %}">List user orders</a>
          </li>
          {% if perms.orders.change_order %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'orders:orders-list' %}">List orders</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <!-- Basket -->
        <a class="navbar-brand position-relative" href="{% url 'orders:view-cart' %}">
          <img src="/media/basket_icon.svg" alt="Bootstrap" width="32" height="32">
          <span class="position-absolute top-32 start-100 translate-middle badge rounded-pill text-bg-danger">{{ cart.total_quantity }}</span>
        </a>
        <!-- Search --> 
        <form class="d-flex" action="/" method="GET" role="search">       
          <input type="search" name="q_search" class="form-control me-2" placeholder="Search..." aria-label="Search">
        </form>
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'logout' %}">{{ user.username }} | Logout</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'login' %}">Login</a>
        {% endif %}
        <!-- Button trigger modal -->
        {% comment %} <button type="button" class="btn btn-outline-light me-2" data-bs-toggle="modal" data-bs-target="#Login">Login</button> {% endcomment %}
        <!-- Modal -->
        {% comment %} <div class="modal fade" id="Login" tabindex="-1">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="loginLabel">Modal Login</h1>
              </div>
              <div class="modal-body">
                LOGIN login LOGIN login LOGIN login
              </div>
              <form action="" method="post">
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Login</button>
                </div>
              </form>
            </div>
          </div>
        </div> {% endcomment %}
      </div>
    </div>
  </nav>
</header>

<!-- Begin page content -->
{% block body %}
No No No
{% endblock body %}

<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">{% block footer %}
    No content now    
    {% endblock footer %}</span>
  </div>
</footer>

</body>
</html>