src/orders/urls.py
from django.urls import path, re_path
from . import views


app_name = "orders"

urlpatterns = [
    path('cart/', views.view_cart, name='view-cart'),
    path('edit_cart/', views.edit_cart, name='edit-cart'),
    path('delete/<int:pk>/', views.DeleteCartBook.as_view(), name='delete-cart'),
    path('order_complete/', views.CreateOrder.as_view(), name='order-complete'),
    path('user_orders/', views.UserOrders.as_view(), name='user-orders'),
    path('order_update/<int:pk>/', views.UpdateOrder.as_view(), name='order-update'),
    path('orderslist/', views.ListOrders.as_view(), name='orders-list'),
   
]

src/proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from homepage.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('', index),
    path('refs/', include('references.urls', namespace="references")),
    path('goods/', include('goods.urls', namespace="goods")),
    path('orders/', include('orders.urls', namespace="orders"))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
statuses = (
    ('In progress', "In progress"),
    ('Sended', "Sended"),
    ('Done', "Done"),
)

# Create your models here.


class Cart(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='User cart',
        related_name='carts',
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )
    def total_quantity(self):
        all_books_in_cart = self.book.all()
        total_quantity = 0
        for books_quantity in all_books_in_cart:
            total_quantity += books_quantity.quantity
        return total_quantity

    def total_price(self):
        total_price_in_cart = self.book.all()
        total_price = 0
        for price in total_price_in_cart:
            total_price += price.price_per_position()
        return total_price

    # def __str__(self):
    #     return self.user

class BookinCart(models.Model):
    book = models.ForeignKey(
        "goods.GoodsBooks",
        verbose_name='Book in a cart',
        on_delete=models.PROTECT,
    )
    cart = models.ForeignKey(
        "orders.Cart",
        verbose_name='Cart',
        related_name='book',
        on_delete=models.PROTECT,
    )
    quantity = models.IntegerField(
        verbose_name='Quantity',
        default=1
    )
    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
    )
    create_date = models.DateTimeField(
        "Create date",
        auto_now=False,
        auto_now_add=True
    )
    update_date = models.DateTimeField(
        "Update date",
        auto_now=True,
        auto_now_add=False
    )
    def price_per_position(self):
        return self.price * self. quantity

    def __str__(self):
        return self.book

class Order(models.Model):
    status = models.CharField(
        verbose_name='Status',
        max_length=20,
        choices=statuses,
        default='In progress'
    )
    cart = models.OneToOneField(
        "orders.Cart",
        verbose_name='Cart',
        related_name='order',
        on_delete=models.PROTECT,
    )
    phone = models.CharField(
        verbose_name='Phone',
        max_length=50,
    )
    name = models.CharField(
        verbose_name='Name',
        max_length=20
    )
    adress = models.CharField(
        verbose_name='Adress',
        max_length=100,
    )
    email = models.EmailField(
        verbose_name='Email',
        max_length=100,
    )
    info = models.TextField(
        verbose_name='Info',
        max_length=500,
    )
    create_date = models.DateTimeField(
        "Create date",
        auto_now=False,
        auto_now_add=True
    )
    update_date = models.DateTimeField(
        "Update date",
        auto_now=True,
        auto_now_add=False
    )

src/orders/forms.py
from django import forms
from django.contrib.auth.models import User



from . import models


class BookinCartForm(forms.ModelForm):
    class Meta:
        model = models.BookinCart
        fields = '__all__'

class OrderForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = [
            'status',
            'phone',
            'name',
            'adress',
            'email',
            'info'
        ]
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        self.view_order = kwargs.pop('view_order')
        print(self.request.user)
        print(self.view_order)
        super().__init__(*args, **kwargs)
        if self.view_order == True:
            self.fields['status'].widget.attrs['hidden'] = True
        elif self.view_order == False:
            if not self.request.user.is_superuser:
                self.fields['status'].widget.attrs['disabled'] = True
                self.fields['phone'].widget.attrs['disabled'] = True
                self.fields['name'].widget.attrs['disabled'] = True
                self.fields['adress'].widget.attrs['disabled'] = True
                self.fields['email'].widget.attrs['disabled'] = True
                self.fields['info'].widget.attrs['disabled'] = True
        # if self.request.user.is_anonymous:
        #     self.fields['status'].widget.attrs['disabled'] = True            
        #     if self.view_order == True:
        #         del self.fields['status']
        #     else:
        #         self.fields['status'].widget.attrs['disabled'] = True
        #         self.fields['phone'].widget.attrs['disabled'] = True
        #         self.fields['name'].widget.attrs['disabled'] = True
        #         self.fields['adress'].widget.attrs['disabled'] = True
        #         self.fields['email'].widget.attrs['disabled'] = True
        #         self.fields['info'].widget.attrs['disabled'] = True
                

src/orders/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin

from . import models, forms
from goods import  models as goods_models

# Create your views here.

# class PassRequestToFormViewMixin:
#     def get_form_kwargs(self):
#         kwargs = super().get_form_kwargs()
#         kwargs['request'] = self.request
#         return kwargs

def view_cart(request):
    context = {} 

    if request.method == 'POST':
        book_pk = int(request.POST.get('book_pk'))
        quantity = int(request.POST.get('quantity'))
        user = request.user
        
        print(book_pk)
        print(quantity)
        print(user.carts)
        
        if book_pk and quantity:
            cart_id = request.session.get('cart_id')
                        
            if request.user.is_authenticated:
                user = request.user
            else:
                user = None

            cart, created = models.Cart.objects.get_or_create(
                pk=cart_id,
                defaults={
                    'user': user
                }
            )
            print(user)
            print (cart.pk)
            if created:
                request.session['cart_id'] = cart.pk
                
            cart_id = cart.pk
            print (cart_id)
            book = goods_models.GoodsBooks.objects.get(pk=book_pk)
            price = book.price

            book_in_cart, created = models.BookinCart.objects.get_or_create(
                book=book,
                cart=cart,
                defaults={
                    'quantity': quantity,
                    'price': price
                }
            )
            
            if not created:
                change_quantity = request.POST.get('change_quantity')
                if change_quantity != None:
                    book_in_cart.quantity = int(change_quantity)
                else:
                    book_in_cart.quantity += quantity
                book_in_cart.save()                     
    else:
        cart_id = request.session.get('cart_id') 

    cart = models.Cart.objects.get(pk=cart_id)
    # print(cart)
    context['cart'] = cart
    context['form'] = forms.OrderForm(
        request=request,
        view_order = True
        )
    return render(
        request, 
        template_name='orders/view_cart.html',
        context = context            
        )

class CreateOrder(generic.CreateView):
    model = models.Order
    template_name ='orders/order_complete.html'
    form_class = forms.OrderForm
    success_url = reverse_lazy('orders:order-complete')

    def form_valid(self, form):
        cart_id = self.request.session.get('cart_id')
        cart = models.Cart.objects.get(pk=cart_id)
        form.instance.cart = cart
        return super().form_valid(form)

    def get_success_url(self) -> str:
        del self.request.session['cart_id']
        return super().get_success_url()
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        cart_id = self.request.session.get('cart_id')
        if cart_id:
            cart = models.Cart.objects.get(pk=cart_id)
            context['cart'] = cart

        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        view_order = False
        kwargs.update({'request': self.request, 'view_order': view_order})
        return kwargs

class UserOrders(generic.ListView):
    model = models.Order
    template_name = 'orders/user_orders.html'
    success_url = reverse_lazy('orders:user-orders')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        user = self.request.user
        print(user)
        cart = user.carts.all()
        print(cart)
        context['cart'] = cart

        return context

def edit_cart(request):
    context = {} 

    if request.method == 'POST':
        book_pk = int(request.POST.get('book_pk'))
        change_quantity = int(request.POST.get('change_quantity'))
        order_pk = int(request.POST.get('order_pk'))
        print(book_pk)
        print(order_pk)
        print(change_quantity)
        if book_pk and change_quantity:
            book_in_cart = models.BookinCart.objects.get(pk=book_pk)
            book_in_cart.quantity = int(change_quantity)
            book_in_cart.save()

    orders = models.Order.objects.all()
    context['orders'] = orders
    return render(
        request,
        # template_name='orders/orders_update/order_pk',
        template_name='orders/orders_list.html',
        context = context
    ) 

class UpdateOrder(PermissionRequiredMixin, generic.UpdateView):
    model = models.Order
    template_name ='orders/order_update.html'
    form_class = forms.OrderForm
    permission_required = 'orders.change_order'
    success_url = reverse_lazy('orders:orders-list')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        cart_id = self.object.cart.pk
        print(cart_id + 20000)
        cart = models.Cart.objects.get(pk=cart_id)
        order_pk = self.object.pk
        print(order_pk)
        context['cart'] = cart
        context['order_pk'] = order_pk
        # orders = models.Order.objects.all()
        # context['orders'] = orders
        print(cart.order.status)
        print(cart.order.phone)
        
        # object_temp = context.get('object')
        # print(object_temp)
        # object_temp.status = cart.order.status
        # object_temp.phone = cart.order.phone
        # object_temp.name = cart.order.name
        # object_temp.adress = cart.order.adress
        # object_temp.email = cart.order.email
        # object_temp.info = cart.order.info
        # del context['form']
        # context['form'] = forms.OrderForm(instance=object_temp, request=self.request)
        # context['form'] = form
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        view_order = False
        kwargs.update({'request': self.request, 'view_order': view_order})
        return kwargs

class ListOrders(PermissionRequiredMixin, generic.ListView):
    model =models.Order
    template_name ='orders/orders_list.html'
    permission_required = 'orders.change_order'
    success_url = reverse_lazy('orders:orders-list')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        orders = models.Order.objects.all()
        context['orders'] = orders
        return context

class DeleteCartBook(generic.DeleteView):
    model = models.BookinCart
    template_name ='orders/view_cart.html'
    success_url = reverse_lazy('orders:view-cart') 

src/orders/templates/orders/order_complete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}

{% endblock title %}

{% block body %}
<main class="flex-shrink-0">
    <div class="container">
        <h1>Order complete</h1>
        <table class="table table-hover table-sm">
            <thead><th colspan="2">pk</th><th>book</th><th>quantity</th><th>price</th><th>price_per_position</th><th>create_date</th><th>update_date</th></thead>
            {% for book_in_cart in cart.book.all %}        
                <tr>
                    <td>{{ book_in_cart.pk }}</td>
                    <td><img src="{{ book_in_cart.book.cover.url }}" width="32" height="48"></td>
                    <td>{{ book_in_cart.book }}</td>
                    <td>
                        <form action="{% url 'orders:view-cart' %}" method="post">
                            {% csrf_token %}
                            <div class="input-group input-group-sm">                    
                                <input type="number" class="form-control" style="width: 4rem" value="{{ book_in_cart.quantity }}" disabled>
                                <input type="hidden" name="book_pk" value="{{ book_in_cart.book.pk }}">
                                <input type="hidden" name="quantity" value="{{ book_in_cart.quantity }}">
                                <button type="submit" class="btn btn-outline-secondary" disabled>Change</button>                                          
                            </div>
                        </form>
                    </td>
                    <td>{{ book_in_cart.price }}</td>
                    <td>{{ book_in_cart.price_per_position }}</td>
                    <td>{{ book_in_cart.create_date }}</td>
                    <td>{{ book_in_cart.update_date }}</td>
                    <td>
                        {% comment %} <form action="{% url 'orders:delete-cart' pk=book_in_cart.pk %}" method="post">
                            {% csrf_token %} 
                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                        </form> {% endcomment %}
                    </td>
                </tr>
            {% endfor %}
            <h3><th colspan="3">{{ cart.book.count }}</th><th>{{ cart.total_quantity }}</th><th>Total price:</th><th colspan="4">{{ cart.total_price }}</th></h3>                      
        </table> 
        {% comment %} <div class="row row-cols-2">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-outline-success">Order</button>
            </form> 
        </div>         {% endcomment %}
    </div>
</main>
{% endblock body %}

{% block footer %}
cart
{% endblock footer %}
    

src/orders/templates/orders/order_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}

{% endblock title %}

{% block body %}
<main class="flex-shrink-0">
    <div class="container">
        <h1>Order complete</h1>
        <table class="table table-hover table-sm">
            <thead><th colspan="2">pk</th><th>book</th><th>quantity</th><th>price</th><th>price_per_position</th><th>create_date</th><th>update_date</th></thead>
            {% for book_in_cart in cart.book.all %}        
                <tr>
                    <td>{{ book_in_cart.pk }}</td>
                    <td><img src="{{ book_in_cart.book.cover.url }}" width="32" height="48"></td>
                    <td>{{ book_in_cart.book }}</td>
                    <td>
                        <form action="{% url 'orders:edit-cart' %}" method="post">
                            {% csrf_token %}
                            <div class="input-group input-group-sm">                    
                                <input type="number" name="change_quantity" class="form-control" style="width: 4rem" value="{{ book_in_cart.quantity }}">
                                <input type="hidden" name="book_pk" value="{{ book_in_cart.pk }}">
                                <input type="hidden" name="order_pk" value="{{ order_pk }}">
                                <button type="submit" class="btn btn-outline-secondary">Change</button>                                          
                            </div>
                        </form>
                    </td>
                    <td>{{ book_in_cart.price }}</td>
                    <td>{{ book_in_cart.price_per_position }}</td>
                    <td>{{ book_in_cart.create_date }}</td>
                    <td>{{ book_in_cart.update_date }}</td>
                    <td>
                        {% comment %} <form action="{% url 'orders:delete-cart' pk=book_in_cart.pk %}" method="post">
                            {% csrf_token %} 
                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                        </form> {% endcomment %}
                    </td>
                </tr>
            {% endfor %}
            <h3><th colspan="3">{{ cart.book.count }}</th><th>{{ cart.total_quantity }}</th><th>Total price:</th><th colspan="4">{{ cart.total_price }}</th></h3>                      
        </table>
        <div class="row row-cols-2">
            <form action="{% url 'orders:order-update' pk=order.pk %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-outline-success">Save</button>
            </form> 
        </div>        
    </div>
</main>
{% endblock body %}

{% block footer %}
cart
{% endblock footer %}
    

src/orders/templates/orders/orders_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}

{% endblock title %}

{% block body %}
<main class="flex-shrink-0">
    <div class="container">
        <h1>Order list</h1>
        <table class="table table-hover table-sm">
            <thead><th>pk</th><th>status</th><th>total_price</th><th>phone</th><th>name</th><th>adress</th><th>email</th><th>info</th><th>create_date</th><th>update_date</th></thead>
            {% for order in orders %}        
                <tr onclick="location.href='{% url 'orders:order-update' pk=order.pk %}'">
                    <td>{{ order.pk }}</td>
                    <td style="background-color: #62a3d0">{{ order.status }}</td>
                    <td>{{ order.cart.total_price }}</td>
                    <td>{{ order.phone }}</td>
                    <td>{{ order.name }}</td>
                    <td>{{ order.adress }}</td>
                    <td>{{ order.email }}</td>
                    <td>{{ order.info }}</td>
                    <td>{{ order.create_date }}</td>
                    <td>{{ order.update_date }}</td>                    
                </tr>
            {% endfor %}
        </table>
    </div>
</main>
{% endblock body %}

{% block footer %}
cart
{% endblock footer %}
    

src/orders/templates/orders/user_orders.html
{% extends "base.html" %}

{% block title %}

{% endblock title %}

{% block body %}
<main class="flex-shrink-0">
    <div class="container">
        <h1>All orders</h1>
        <table class="table table-hover table-sm">
            <thead><th>pk</th><th>status</th><th>total_price</th><th>phone</th><th>name</th><th>adress</th><th>email</th><th>info</th><th>create_date</th><th>update_date</th></thead>
            {% for order in cart %}        
                <tr>
                    <td>{{ order.order.pk }}</td>
                    <td style="background-color: #62a3d0">{{ order.order.status }}</td>
                    <td>{{ order.order.cart.total_price }}</td>
                    <td>{{ order.order.phone }}</td>
                    <td>{{ order.order.name }}</td>
                    <td>{{ order.order.adress }}</td>
                    <td>{{ order.order.email }}</td>
                    <td>{{ order.order.info }}</td>
                    <td>{{ order.order.create_date }}</td>
                    <td>{{ order.order.update_date }}</td>
                </tr>
            {% endfor %}                      
        </table>        
    </div>
</main>
{% endblock body %}

{% block footer %}
cart
{% endblock footer %}
    

src/orders/templates/orders/view_cart.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}

{% endblock title %}

{% block body %}
<main class="flex-shrink-0">
    <div class="container">
        <h1>Cart</h1>
        <table class="table table-hover table-sm">
            <thead><th colspan="2">pk</th><th>book</th><th>quantity</th><th>price</th><th>price_per_position</th><th>create_date</th><th>update_date</th></thead>
            {% for book_in_cart in cart.book.all %}        
                <tr>
                    <td>{{ book_in_cart.pk }}</td>
                    <td><img src="{{ book_in_cart.book.cover.url }}" width="32" height="48"></td>
                    <td>{{ book_in_cart.book }}</td>
                    <td>
                        <form action="{% url 'orders:view-cart' %}" method="post">
                            {% csrf_token %}
                            <div class="input-group input-group-sm">                    
                                <input type="number" class="form-control" name="change_quantity" style="width: 4rem" value="{{ book_in_cart.quantity }}" step="1" min="1">
                                <input type="hidden" name="book_pk" value="{{ book_in_cart.book.pk }}">
                                <input type="hidden" name="quantity" value="{{ book_in_cart.quantity }}">
                                <button type="submit" class="btn btn-outline-secondary">Change</button>                                          
                            </div>
                        </form>
                    </td>
                    <td>{{ book_in_cart.price }}</td>
                    <td>{{ book_in_cart.price_per_position }}</td>
                    <td>{{ book_in_cart.create_date }}</td>
                    <td>{{ book_in_cart.update_date }}</td>
                    <td>
                        <form action="{% url 'orders:delete-cart' pk=book_in_cart.pk %}" method="post">
                            {% csrf_token %} 
                            <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            <h3><th colspan="3">{{ cart.book.count }}</th><th>{{ cart.total_quantity }}</th><th>Total price:</th><th colspan="4">{{ cart.total_price }}</th></h3>                      
        </table>
        <div class="row row-cols-2">
            <form action="{% url 'orders:order-complete' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Order</button>
            </form> 
        </div>        
    </div>
</main>
{% endblock body %}

{% block footer %}
cart
{% endblock footer %}
    